/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class Amex
    {
        /// <summary>
        /// DpaData data should be provided to SRC system if srcDpaId is not provided.
        /// </summary>
        public DpaData DpaData { get; set; }

        /// <summary>
        /// DPA configuration data that can override any configuration set before.
        /// </summary>
        public DpaTransactionOptions DpaTransactionOptions { get; set; }

        /// <summary>
        /// SRCI identifier. This is generated by the SRC System during onboarding.
        /// </summary>
        public string SrcInitiatorId { get; set; }
    }
}
