/*
 * This file was automatically generated.
 */
using System;
using System.Collections.Generic;

namespace OnlinePayments.Sdk.Domain
{
    public class CreateHostedTokenizationResponse
    {
        /// <summary>
        /// Tokens referencing expired cards are returned in this array.
        /// These tokens can be used in the hosted tokenization session but you must ensure that the expiry date fields are displayed in the form in order to be updated.
        /// If you are using the option &quot;hideTokenFields&quot;, these tokens should not be proposed to the customers.
        /// </summary>
        public IList<string> ExpiredCardTokens { get; set; }

        /// <summary>
        /// The ID of the Hosted Tokenization Session
        /// </summary>
        public string HostedTokenizationId { get; set; }

        /// <summary>
        /// The URL you can use in your JavaScript when instantiating the Tokenizer.
        /// </summary>
        public string HostedTokenizationUrl { get; set; }

        /// <summary>
        /// Tokens that are submitted in the request are validated. Tokens that cannot be used in the current session are returned in this array.
        /// These tokens might not be valid anymore. The validity of tokens can be verified using the <a href="#operation/GetTokenApi">Get token</a> endpoint.
        /// </summary>
        public IList<string> InvalidTokens { get; set; }

        /// <summary>
        /// Deprecated. Use hostedTokenizationUrl instead.
        /// <p />
        /// The partial URL as generated by our system. You will need to add the protocol and the relevant subdomain to this URL, before redirecting your customer to this URL. A special 'payment' subdomain will always work so you can always add 'https://payment.' at the beginning of this response value to view your hosted pages.
        /// </summary>
        [Obsolete("Deprecated")]
        public string PartialRedirectUrl { get; set; }
    }
}
