/*
 * This file was automatically generated.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace OnlinePayments.Sdk.Domain
{
    public class CreateHostedCheckoutResponse
    {
        /// <summary>
        /// When the customer is returned to your site we will append this property and value to the query-string. You should store this data, so you can identify the returning customer.
        /// </summary>
        [JsonProperty(PropertyName = "RETURNMAC")]
        public string RETURNMAC { get; set; }

        /// <summary>
        /// The ID of the Hosted Checkout Session in which the payment was made.
        /// </summary>
        public string HostedCheckoutId { get; set; }

        public IList<string> InvalidTokens { get; set; }

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.
        /// It is highly recommended to provide a single MerchantReference per unique order on your side
        /// </summary>
        public string MerchantReference { get; set; }

        /// <summary>
        /// The partial URL as generated by our system. You will need to add the protocol and the relevant subdomain to this URL, before redirecting your customer to this URL. A special 'payment' subdomain will always work so you can always add 'https://payment.' at the beginning of this response value to view your hosted pages.
        /// </summary>
        public string PartialRedirectUrl { get; set; }

        /// <summary>
        /// The full hosted checkout URL as generated by our system. Use this URL to redirect your customer to the hosted checkout page.
        /// </summary>
        public string RedirectUrl { get; set; }
    }
}
