/*
 * This class was auto-generated.
 */
using Newtonsoft.Json;
using System.Collections.Generic;

namespace OnlinePayments.Sdk.Domain
{
    public class CreateHostedCheckoutResponse
    {
        [JsonProperty(PropertyName = "RETURNMAC")]
        /// <summary>
        /// When the customer is returned to your site we will append this property and value to the query-string. You should store this data, so you can identify the returning customer.<para />
        /// </summary>
        public string RETURNMAC { get; set; } = null;

        /// <summary>
        /// The ID of the Hosted Checkout Session in which the payment was made.<para />
        /// </summary>
        public string HostedCheckoutId { get; set; } = null;

        /// <summary>
        /// Tokens that are submitted in the request are validated. In case any of the tokens can't be used anymore they are returned in this array. You should most likely remove those tokens from your system.<para />
        /// </summary>
        public IList<string> InvalidTokens { get; set; } = null;

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.<para />
        /// </summary>
        public string MerchantReference { get; set; } = null;

        /// <summary>
        /// The partial URL as generated by our system. You will need to add the protocol and the relevant subdomain to this URL, before redirecting your customer to this URL. A special 'payment' subdomain will always work so you can always add 'https://payment.' at the beginning of this response value to view your hosted pages.<para />
        /// </summary>
        public string PartialRedirectUrl { get; set; } = null;
    }
}
