/*
 * This class was auto-generated.
 */
using System.Collections.Generic;

namespace OnlinePayments.Sdk.Domain
{
    public class CreateHostedTokenizationResponse
    {
        /// <summary>
        /// Tokens referencing expired cards are returned in this array. <para />
        /// These tokens can be used in the hosted tokenization session but you must ensure that the expiry date fields are displayed in the form in order to be updated.<para />
        /// If you are using the option "hideTokenFields", these tokens should not be proposed to the customers.<para />
        /// </summary>
        public IList<string> ExpiredCardTokens { get; set; } = null;

        /// <summary>
        /// The ID of the Hosted Tokenization Session<para />
        /// </summary>
        public string HostedTokenizationId { get; set; } = null;

        /// <summary>
        /// Tokens that are submitted in the request are validated. Tokens that cannot be used in the current session are returned in this array. <para />
        /// These tokens might not be valid anymore. The validity of tokens can be verified using the [Get token](#operation/GetTokenApi) endpoint.<para />
        /// </summary>
        public IList<string> InvalidTokens { get; set; } = null;

        /// <summary>
        /// The partial URL as generated by our system. You will need to add the protocol and the relevant subdomain to this URL, before redirecting your customer to this URL. A special 'payment' subdomain will always work so you can always add 'https://payment.' at the beginning of this response value to view your hosted pages.<para />
        /// </summary>
        public string PartialRedirectUrl { get; set; } = null;
    }
}
