/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class Mastercard
    {
        /// <summary>
        /// Authentication options to execute passkeys or 3DS authentication for transactions.
        /// </summary>
        public AuthenticationOptions AuthenticationOptions { get; set; }

        /// <summary>
        /// Identifier for the integrator. This is generated by the Mastercard System during onboarding.
        /// </summary>
        public string SrcInitiatorId { get; set; }

        /// <summary>
        /// DPA Identifier. This is generated by the integrator during registration.
        /// </summary>
        public string SrciDpaId { get; set; }
    }
}
