/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class Mastercard
    {
        /// <summary>
        /// Authentication options to execute passkeys or 3DS authentication for transactions.
        /// </summary>
        public AuthenticationOptions AuthenticationOptions { get; set; }

        /// <summary>
        /// Identifier for the integrator. This is generated by the Mastercard System during onboarding.
        /// </summary>
        public string SrcInitiatorId { get; set; }

        /// <summary>
        /// DPA Identifier. This is generated by the integrator during registration.
        /// </summary>
        public string SrciDpaId { get; set; }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Mastercard WithAuthenticationOptions(AuthenticationOptions value)
        {
            AuthenticationOptions = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Mastercard WithSrcInitiatorId(string value)
        {
            SrcInitiatorId = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Mastercard WithSrciDpaId(string value)
        {
            SrciDpaId = value;
            return this;
        }
    }
}
