/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class PaymentProduct5002defaultBrandParameters
    {
        /// <summary>
        /// The reference identifier that has been generated either by the SRC Initiator or by the SRC System. During DPA Registration with the SRC System, this value will identify the DPA for subsequent initialisations.
        /// </summary>
        public string SrcDpaId { get; set; }

        /// <summary>
        /// The reference identifier generated by the SRC System during Onboarding of the SRC Initiator to the SRC System.
        /// </summary>
        public string SrcInitiatorId { get; set; }
    }
}
