/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class RedirectPaymentProduct3204SpecificInput
    {
        /// <summary>
        /// Code required for BLIK payments generated by the buyer's bank application
        /// </summary>
        public string BlikCode { get; set; }
    }
}
