/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class RedirectPaymentProduct3204SpecificInput
    {
        /// <summary>
        /// A name that will allow the consumer to identify his/her account in the your web shop (e.g., a masked email address or customer number) after he/she accepts the tokenization in his banking app. The label is especially important if the User has more than one account in the same web shop. This field is mandatory in tokenization use cases.
        /// </summary>
        public string AliasLabel { get; set; }

        /// <summary>
        /// Code required for BLIK payments generated by the buyer's bank application
        /// </summary>
        public string BlikCode { get; set; }
    }
}
