/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class ThreeDSecureResults
    {
        /// <summary>
        /// Authenticated Transaction Identifier at the ACS/Issuer.
        /// </summary>
        public string AcsTransactionId { get; set; }

        /// <summary>
        /// Exemption requested and applied in the authorization
        /// </summary>
        public string AppliedExemption { get; set; }

        /// <summary>
        /// One-letter authentication status returned by DS. Possible values are:
        /// <list type="bullet">
        ///   <item><description>Y - Authentication succeeded</description></item>
        ///   <item><description>A - Authentication attempted</description></item>
        ///   <item><description>I - Information only, liability shifted to the merchant</description></item>
        ///   <item><description>N - Authentication failed</description></item>
        ///   <item><description>R - Authentication rejected</description></item>
        ///   <item><description>U - Authentication unavailable</description></item>
        ///   <item><description>C - Authentication required</description></item>
        /// </list>
        /// </summary>
        public string AuthenticationStatus { get; set; }

        /// <summary>
        /// Cardholder Authentication Verification Value. End-2-end reference generated by the Issuer to recognize that the authentication has taken place.
        /// </summary>
        public string Cavv { get; set; }

        /// <summary>
        /// Challenge Indicator used for this transaction. This value might differ from the one sent by the merchant if the card is not supporting it (3DS version 2.1 vs 3DS version 2.2).
        /// </summary>
        public string ChallengeIndicator { get; set; }

        /// <summary>
        /// 3D Secure Directory Server Transaction Identifier used for this transaction.
        /// </summary>
        public string DsTransactionId { get; set; }

        /// <summary>
        /// Indicates Authentication validation results returned after AuthenticationValidation
        /// </summary>
        public string Eci { get; set; }

        /// <summary>
        /// Detailed description of the Exemption Engine outcomes
        /// </summary>
        public string ExemptionEngineFlow { get; set; }

        /// <summary>
        /// 3D Secure Flow used during this transaction.
        /// </summary>
        public string Flow { get; set; }

        /// <summary>
        /// Determines the Fraud liability. Possible values are:
        /// <list type="bullet">
        ///   <item><description>issuer - Fraud liability shifts to the issuer</description></item>
        ///   <item><description>merchant - Fraud liability with the merchant</description></item>
        /// </list>
        /// <p />
        /// Note: When not filled in Fraud liability is not applicable for the current transaction.
        /// </summary>
        public string Liability { get; set; }

        /// <summary>
        /// 3D Secure ECI (Electronic Commerce Indicator) depending on the Scheme. Returned by DS.
        /// </summary>
        public string SchemeEci { get; set; }

        /// <summary>
        /// 3D Secure Protocol version used during this transaction.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Transaction ID for the Authentication
        /// </summary>
        public string Xid { get; set; }
    }
}
