/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class Visa
    {
        /// <summary>
        /// 3-D Secure options to execute 3DS authentication for transaction.
        /// </summary>
        public VisaAuthenticationOptions AuthenticationOptions { get; set; }

        /// <summary>
        /// KID (Key ID) of the encryption key to encrypt card information before sending it to Visa.
        /// </summary>
        public string EncryptionKey { get; set; }

        /// <summary>
        /// Modulus of the encryption key to encrypt card information before sending it to Visa.
        /// </summary>
        public string NModulus { get; set; }

        /// <summary>
        /// SRCI identifier generated by an SRC system during the onboarding process.
        /// </summary>
        public string SrcInitiatorId { get; set; }

        /// <summary>
        /// A unique ID provided by the SRCI for the DPA, which can be used as an external client ID. Required if srciDpaId in dpaData is not provided.
        /// </summary>
        public string SrciDpaId { get; set; }
    }
}
