/*
 * This file was automatically generated.
 */
namespace OnlinePayments.Sdk.Domain
{
    public class Visa
    {
        /// <summary>
        /// 3-D Secure options to execute 3DS authentication for transaction.
        /// </summary>
        public VisaAuthenticationOptions AuthenticationOptions { get; set; }

        /// <summary>
        /// KID (Key ID) of the encryption key to encrypt card information before sending it to Visa.
        /// </summary>
        public string EncryptionKey { get; set; }

        /// <summary>
        /// Modulus of the encryption key to encrypt card information before sending it to Visa.
        /// </summary>
        public string NModulus { get; set; }

        /// <summary>
        /// SRCI identifier generated by an SRC system during the onboarding process.
        /// </summary>
        public string SrcInitiatorId { get; set; }

        /// <summary>
        /// A unique ID provided by the SRCI for the DPA, which can be used as an external client ID. Required if srciDpaId in dpaData is not provided.
        /// </summary>
        public string SrciDpaId { get; set; }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Visa WithAuthenticationOptions(VisaAuthenticationOptions value)
        {
            AuthenticationOptions = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Visa WithEncryptionKey(string value)
        {
            EncryptionKey = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Visa WithNModulus(string value)
        {
            NModulus = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Visa WithSrcInitiatorId(string value)
        {
            SrcInitiatorId = value;
            return this;
        }

        /// <summary>
        /// Sets the property and returns this same instance.
        /// </summary>
        public Visa WithSrciDpaId(string value)
        {
            SrciDpaId = value;
            return this;
        }
    }
}
